// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// logliknormLR
NumericMatrix logliknormLR(NumericVector yy, NumericMatrix XX_aug, double alpha, int init);
RcppExport SEXP PWD_logliknormLR(SEXP yySEXP, SEXP XX_augSEXP, SEXP alphaSEXP, SEXP initSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type yy(yySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type XX_aug(XX_augSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type init(initSEXP);
    __result = Rcpp::wrap(logliknormLR(yy, XX_aug, alpha, init));
    return __result;
END_RCPP
}
